connections:
  databricks:
    enabled: true
    ingest: true
    host: "https://your-databricks-host"
    token: "your-databricks-token"
    # Additional databricks-specific configurations

  gcs:
    enabled: true
    ingest: true
    bucket_name: "your-gcs-bucket-name"
    project_id: "your-gcs-project-id"
    service_account_key_path: "path/to/your-gcs-sa-key.json"  # Path to the GCS service account key file

  bq:
    enabled: true
    ingest: true
    project_id: "your-bigquery-project-id"
    dataset: "your-dataset-name"
    service_account_key_path: "path/to/your-bq-sa-key.json"  # Path to the BigQuery service account key file

mlflow: 
  mode: local
  local:
    mlflow_tracking_uri: "http://localhost:5000"
    artifact_uri: "file:/path/to/mlruns"
    experiment_name: "your-experiment-name"
  databricks:
    mlflow_tracking_uri: "databricks"
    databricks_host: "host"
    databricks_token: "token"
    experiment_path: "path"

